Plugin Name: ArduinoGC
Plugin Version: 1.4.0
Server Main: com.growcontrol.plugins.arduinogc.ArduinoGC.class
Client Main: com.growcontrol.plugins.arduinogc.gui.ArduinoGC.class
Author: lorenzop
Website: http://www.growcontrol.com/
Depend: []
SoftDepend: []
